version: "3"

services:
    java:
        build: .
        volumes:
            - ".gradle:/work/.gradle"
            - "build:/work/build"
            - ".:/work:cached"
        ports:
            - 8080:8080
    db:
        image: postgres:13.3-alpine
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - LANG=ja_JP.utf8
volumes:
    .gradle:
    build: